#ifndef SIMPLE_NAVIGATOR_CONTROLLER_CONTROLLER_H
#define SIMPLE_NAVIGATOR_CONTROLLER_CONTROLLER_H

namespace s21 {

class Controller {
};

} // namespace s21

#endif  // SIMPLE_NAVIGATOR_CONTROLLER_CONTROLLER_H